// 미리보기용 샘플 캠페인.
// APPS_SCRIPT_URL 이 설정되면 구글시트 '캠페인' 탭 데이터로 대체됩니다.
// 시트의 컬럼 구조도 이 객체와 동일합니다(SETUP.md 참고).

export const SEED_CAMPAIGNS = [
  {
    slug: "oddtype-jun-w2",
    title: "오드타입 6월 2주차 (벌룬/블로우/립라이너/립타투)",
    brand_name: "무신사",
    brand_logo_url: "",
    brand_intro:
      "오드타입(ODDTYPE)은 무신사 뷰티 브랜드로, 개성 있는 컬러와 텍스처의 립 제품 라인을 선보입니다. 벌룬틴트, 블로우립글로스, 립라이너, 립타투 등 다양한 립 포맷을 통해 독창적인 메이크업 룩을 제안합니다.",
    cover_image_url: "",
    content_type: "릴스",
    reward_amount: 50000,
    apply_deadline: "2026-06-28",
    upload_start: "2026-06-11",
    upload_end: "2026-06-17",
    schedule_note: "프로모션 상황에 따라 일정이 변경될 수 있습니다.",
    flags: ["공동작업 필수", "2차활용 필수"],
    applicant_count: 22,
    guide_file_url: "https://example.com/oddtype-guide.pdf",
    required_notes: "전 색상 발색",
    forbidden_notes: "타 브랜드 언급 금지",
    recommended_notes: "고화질 촬영",
    guide_note: "자세한 가이드라인은 선정 시 전달드립니다.",
    collab_accounts: ["@oddtype_official", "@oddtype_jp"],
    required_hashtags: "#무신사 #닥시젤리틴트",
    caption_requirements: "전색상 발색했다고 언급",
    products: [
      { name: "벌룬틴트 4종 (랜덤)", url: "https://www.musinsa.com/products/3882622" },
      { name: "블러틴트 4종 (랜덤)", url: "https://www.musinsa.com/products/3153848" },
      { name: "워터블러시 4종 (랜덤)", url: "https://www.musinsa.com/products/3450028" },
    ],
    products_note:
      "크리에이터 개인 피드 무드 및 콘셉트에 맞춰 브랜드 측에서 최적의 제품군으로 선정 후 발송 예정.",
    consent_items: [
      "선정 후 미업로드 시 제공받은 제품의 원가를 청구받는 데 동의합니다.",
    ],
    status: "open",
  },
  {
    slug: "kippintouch-jun-powder",
    title: "키핀터치 6월 파우더",
    brand_name: "키핀터치",
    brand_logo_url: "",
    brand_intro:
      "키핀터치는 데일리 베이스 메이크업에 강점을 둔 뷰티 브랜드입니다. 가볍고 자연스러운 마무리감의 파우더 신제품을 소개합니다.",
    cover_image_url: "",
    content_type: "릴스",
    reward_amount: 0,
    upload_start: "2026-06-15",
    upload_end: "2026-06-30",
    flags: ["협의"],
    applicant_count: 0,
    guide_file_url: "",
    required_notes: "제품 사용 장면 포함, 발림성 강조",
    forbidden_notes: "과장된 효과 표현 금지",
    recommended_notes: "자연광 촬영",
    collab_accounts: ["@kippintouch_official"],
    required_hashtags: "#키핀터치 #키핀파우더",
    caption_requirements: "제품명 정확히 표기",
    consent_items: [
      "선정 후 미업로드 시 제공받은 제품의 원가를 청구받는 데 동의합니다.",
    ],
    status: "negotiable",
  },
  {
    slug: "offlow-may-collab",
    title: "오플로우 5월 국내 인플루언서 협업",
    brand_name: "오플로우",
    brand_logo_url: "",
    brand_intro:
      "오플로우(OFFLOW)는 클렌징 도구 및 뷰티 액세서리 브랜드입니다. 부드러운 사용감의 클렌징 스펀지를 선보입니다.",
    cover_image_url: "",
    content_type: "릴스",
    reward_amount: 50000,
    upload_start: "2026-06-01",
    upload_end: "2026-06-20",
    flags: ["공동작업 필수"],
    applicant_count: 1,
    guide_file_url: "",
    required_notes: "사용 전/후 비교 장면 포함",
    forbidden_notes: "타 브랜드 동시 노출 금지",
    recommended_notes: "클로즈업 컷 활용",
    collab_accounts: ["@offlow_official"],
    required_hashtags: "#오플로우 #클렌징스펀지",
    caption_requirements: "브랜드 계정 멘션",
    consent_items: [
      "선정 후 미업로드 시 제공받은 제품의 원가를 청구받는 데 동의합니다.",
    ],
    status: "open",
  },
  {
    slug: "musinsa-jun-feed",
    title: "6월 피드 급건",
    brand_name: "무신사",
    brand_logo_url: "",
    brand_intro:
      "무신사 뷰티 PB 제품의 6월 피드 콘텐츠를 빠르게 모집합니다. 스킨케어 룩과 데일리 메이크업을 자연스럽게 담아주세요.",
    cover_image_url: "",
    content_type: "피드",
    reward_amount: 50000,
    upload_start: "2026-06-18",
    upload_end: "2026-06-28",
    flags: ["피드"],
    applicant_count: 1,
    guide_file_url: "",
    required_notes: "피드 2장 이상, 제품 정면 컷 포함",
    forbidden_notes: "필터 과다 사용 금지",
    recommended_notes: "톤온톤 배경",
    collab_accounts: ["@musinsa_beauty"],
    required_hashtags: "#무신사뷰티 #6월신상",
    caption_requirements: "제품 사용 후기 1줄 이상",
    consent_items: [
      "선정 후 미업로드 시 제공받은 제품의 원가를 청구받는 데 동의합니다.",
    ],
    status: "open",
  },
];
